#!/usr/bin/env python3
"""Convert Verilator VCD activity to a simple SAIF 2.0 file.

The converter preserves VCD hierarchy and aggregates multi-bit bus activity into
SAIF T0/T1/TX/TZ/TC counters. It is intended for Vivado power annotation from
the VCD files generated by sim/gen_vcd.sh.
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path


@dataclass
class Signal:
    width: int
    names: list[str] = field(default_factory=list)
    last: str | None = None
    last_time: int = 0
    t0: int = 0
    t1: int = 0
    tx: int = 0
    tz: int = 0
    tc: int = 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("vcd", type=Path)
    parser.add_argument("saif", type=Path)
    parser.add_argument(
        "--strip-prefix",
        action="append",
        default=[],
        help="Drop matching hierarchy prefix from emitted paths. May be repeated.",
    )
    parser.add_argument(
        "--include-prefix",
        action="append",
        default=[],
        help="Emit only paths under this hierarchy prefix. May be repeated.",
    )
    parser.add_argument(
        "--design",
        default=None,
        help="Optional SAIF DESIGN name. Defaults to the VCD stem.",
    )
    parser.add_argument(
        "--root-instance",
        default=None,
        help="Wrap emitted activity in this INSTANCE name. Useful with --strip-prefix.",
    )
    parser.add_argument(
        "--time-multiplier",
        type=int,
        default=1,
        help="Scale T0/T1/TX/TZ/DURATION by this factor; TC is unchanged.",
    )
    return parser.parse_args()


def clean_scope_ref(name: str) -> str:
    # Verilator VCD references include packed ranges as a trailing token, e.g.
    # "State_Reg[0] [127:0]". SAIF name matching is usually better with the RTL
    # object name, so strip only that final packed range and preserve unpacked
    # array indices such as State_Reg[0].
    return re.sub(r"\s+\[[0-9]+(?::[0-9]+)?\]$", "", name.strip())


def parse_vcd_header(path: Path) -> tuple[dict[str, Signal], str]:
    signals: dict[str, Signal] = {}
    scope: list[str] = []
    timescale = "1 ps"

    with path.open(errors="replace") as handle:
        for raw in handle:
            line = raw.strip()
            if not line:
                continue
            parts = line.split()
            if parts[:1] == ["$timescale"] and "$end" in parts:
                end = parts.index("$end")
                timescale = " ".join(parts[1:end])
                if len(parts[1:end]) == 1:
                    packed = parts[1]
                    for unit in ("fs", "ps", "ns", "us", "ms", "s"):
                        if packed.endswith(unit) and packed != unit:
                            timescale = f"{packed[:-len(unit)]} {unit}"
                            break
            elif parts[:2] == ["$scope", "module"] and len(parts) >= 3:
                scope.append(parts[2])
            elif parts[:1] == ["$upscope"]:
                if scope:
                    scope.pop()
            elif parts[:1] == ["$var"]:
                try:
                    width = int(parts[2])
                    code = parts[3]
                    end = parts.index("$end") if "$end" in parts else len(parts)
                    ref = clean_scope_ref(" ".join(parts[4:end]))
                except (ValueError, IndexError):
                    continue
                signal = signals.setdefault(code, Signal(width=width))
                signal.width = max(signal.width, width)
                signal.names.append("/".join(scope + [ref]))
            elif line == "$enddefinitions $end":
                break

    return signals, timescale


def normalize_value(value: str, width: int) -> str:
    value = value.lower()
    if len(value) < width:
        pad = value[0] if value and value[0] in "xz" else "0"
        value = value.rjust(width, pad)
    return value[-width:]


def add_duration(signal: Signal, now: int) -> None:
    if signal.last is None:
        signal.last_time = now
        return
    duration = now - signal.last_time
    if duration <= 0:
        signal.last_time = now
        return

    for bit in signal.last:
        if bit == "0":
            signal.t0 += duration
        elif bit == "1":
            signal.t1 += duration
        elif bit == "z":
            signal.tz += duration
        else:
            signal.tx += duration
    signal.last_time = now


def add_toggle(signal: Signal, value: str) -> None:
    if signal.last is None:
        return
    signal.tc += sum(
        1
        for old, new in zip(signal.last, value)
        if old in "01" and new in "01" and old != new
    )


def parse_vcd_activity(path: Path, signals: dict[str, Signal]) -> tuple[int, int]:
    in_header = True
    time = 0
    first_time: int | None = None
    last_time = 0

    with path.open(errors="replace") as handle:
        for raw in handle:
            line = raw.strip()
            if not line:
                continue
            if in_header:
                if line == "$enddefinitions $end":
                    in_header = False
                continue
            if line.startswith("$"):
                continue
            if line.startswith("#"):
                time = int(line[1:])
                if first_time is None:
                    first_time = time
                last_time = time
                continue

            if line[0] in "01xXzZ":
                code = line[1:]
                value = line[0]
            elif line[0] in "bB":
                parts = line.split()
                if len(parts) < 2:
                    continue
                value = parts[0][1:]
                code = parts[1]
            else:
                continue

            signal = signals.get(code)
            if signal is None:
                continue
            value = normalize_value(value, signal.width)
            add_duration(signal, time)
            add_toggle(signal, value)
            signal.last = value

    for signal in signals.values():
        add_duration(signal, last_time)

    return first_time or 0, last_time


def strip_prefix(path: str, prefixes: list[str]) -> str | None:
    for prefix in prefixes:
        prefix = prefix.strip("/")
        if path == prefix:
            return None
        if path.startswith(prefix + "/"):
            return path[len(prefix) + 1 :]
    return path


def matches_prefix(path: str, prefixes: list[str]) -> bool:
    if not prefixes:
        return True
    path = path.strip("/")
    for prefix in prefixes:
        prefix = prefix.strip("/")
        if path == prefix or path.startswith(prefix + "/"):
            return True
    return False


def saif_name(name: str) -> str:
    escaped = name.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def build_tree(signals: dict[str, Signal], prefixes: list[str], include_prefixes: list[str]) -> dict:
    tree: dict = {"nets": [], "children": defaultdict(lambda: {"nets": [], "children": defaultdict(dict)})}

    def child(node: dict, name: str) -> dict:
        children = node.setdefault("children", {})
        if name not in children:
            children[name] = {"nets": [], "children": {}}
        return children[name]

    for signal in signals.values():
        for raw_name in signal.names:
            if not matches_prefix(raw_name, include_prefixes):
                continue
            name = strip_prefix(raw_name, prefixes)
            if not name:
                continue
            parts = name.split("/")
            if not parts:
                continue
            node = tree
            for inst in parts[:-1]:
                node = child(node, inst)
            node.setdefault("nets", []).append((parts[-1], signal))

    return tree


def scaled(value: int, multiplier: int) -> int:
    return value * multiplier


def write_instance(handle, name: str, node: dict, indent: int, time_multiplier: int) -> None:
    pad = "  " * indent
    handle.write(f"{pad}(INSTANCE {saif_name(name)}\n")
    nets = sorted(node.get("nets", []), key=lambda item: item[0])
    if nets:
        handle.write(f"{pad}  (NET\n")
        for net_name, signal in nets:
            handle.write(
                f"{pad}    ({saif_name(net_name)} "
                f"(T0 {scaled(signal.t0, time_multiplier)}) "
                f"(T1 {scaled(signal.t1, time_multiplier)}) "
                f"(TX {scaled(signal.tx, time_multiplier)}) "
                f"(TZ {scaled(signal.tz, time_multiplier)}) "
                f"(TC {signal.tc}))\n"
            )
        handle.write(f"{pad}  )\n")
    for child_name, child_node in sorted(node.get("children", {}).items()):
        write_instance(handle, child_name, child_node, indent + 1, time_multiplier)
    handle.write(f"{pad})\n")


def write_saif(
    path: Path,
    design: str,
    timescale: str,
    duration: int,
    signals: dict[str, Signal],
    prefixes: list[str],
    include_prefixes: list[str],
    root_instance: str | None,
    time_multiplier: int,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tree = build_tree(signals, prefixes, include_prefixes)
    with path.open("w") as handle:
        handle.write("(SAIFILE\n")
        handle.write('  (SAIFVERSION "2.0")\n')
        handle.write('  (DIRECTION "backward")\n')
        handle.write(f"  (DESIGN {saif_name(design)})\n")
        handle.write(f"  (DATE {saif_name(datetime.now().isoformat(timespec='seconds'))})\n")
        handle.write('  (VENDOR "OpenAI Codex")\n')
        handle.write('  (PROGRAM_NAME "sim/vcd_to_saif.py")\n')
        handle.write('  (VERSION "1.0")\n')
        handle.write("  (DIVIDER /)\n")
        handle.write(f"  (TIMESCALE {timescale})\n")
        handle.write(f"  (DURATION {scaled(duration, time_multiplier)})\n")
        if root_instance:
            write_instance(handle, root_instance, tree, 1, time_multiplier)
        else:
            for child_name, child_node in sorted(tree.get("children", {}).items()):
                write_instance(handle, child_name, child_node, 1, time_multiplier)
        handle.write(")\n")


def main() -> None:
    args = parse_args()
    signals, timescale = parse_vcd_header(args.vcd)
    first_time, last_time = parse_vcd_activity(args.vcd, signals)
    design = args.design or args.vcd.stem
    write_saif(
        path=args.saif,
        design=design,
        timescale=timescale,
        duration=last_time - first_time,
        signals=signals,
        prefixes=args.strip_prefix,
        include_prefixes=args.include_prefix,
        root_instance=args.root_instance,
        time_multiplier=args.time_multiplier,
    )


if __name__ == "__main__":
    main()
